global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor' # Docker container metrics
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'weather-api' # .NET Core app metrics
    static_configs:
      - targets: ['weather-api:5170']